version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASSWORD=YourRootPassword
      - DB_NAME=example
      - DB_PORT=3306
      - NODE_ENV=development
    networks:
      - app-network

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: YourRootPassword
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: YourRootPassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
